### ISSUE TITLE
Problem loading plugin when running master (0.7.0)

### ISSUE THREAD

**Issue by henrikekblad** [psychobunny/nodebb-plugin-events#8]
```

21/5 19:37 [8159] - error: Error: Cannot find module '../public/src/translator'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at Object.<anonymous> (/usr/mysensors/mysensors-forum/NodeBB/node_modules/nodebb-plugin-events/library.js:9:29)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
21/5 19:37 [8159] - warn: [plugins.reload] Library not found for plugin: nodebb-plugin-events
```

**Comment by ornithes** [comment]
up? @psychobunny
